### ISSUE TITLE
feature request: reintroduce dynamic lighting from early Festoon Player version

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#115]

**Comment by phileday** [comment]
There wasn't any dynamic lighting before.

The only thing that's changed in this version is that the lighting option in dome and cinema have been moved to the main window and they have been linked so that turning up the brightness on one turns up the brightness on the other.

At least that is what I believe I've done.

Can you explain the dynamic lighting effect you are referring too? In the player I made for the Quest when we went to Salford the player had dynamic lighting so the video lights up the cinema seats making it brighter in the room when the video was brighter. Is this what you're referring too? It's not in the player but it could be added although I need to see if I can switch between the two as there is a compromise that occurs when doing this.

**Comment by NicholasWaterton** [comment]
Hi Philippa, sorry for not being more specific. Yes, that's the one I'm referring to. It looked fantastic and added to the immersion, not that it's very important in terms of functionality.
