### ISSUE TITLE
2.24_bug_After Effects caused Festoon to crash

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#133]
I know this could well not be an issue with Festoon but I'll flag anyway. A python script running in the background opens After Effects to convert an image sequence. A moment before the render began, Festoon crashed and the Festoon window closed, which you can see from the taskbar. After Effects uses SteamVR for its "Immersive Environment", maybe it's related to this.

video:
https://www.youtube.com/watch?v=NOHvA2rC9-0

**Comment by phileday** [comment]
Actually this isn't a cash and an error. It's because After Effects also have VR features. Steam sees another app with VR open and closes down Festoon.

You can easily fix this by changing that setting.

Here's a video I did to fix this:
https://www.dropbox.com/s/nrhn4ikkvqy3dfi/Festoon%20with%20After%20Effects.mp4?dl=0

Let me know if this isn't what you're talking about.

**Comment by NicholasWaterton** [comment]
Great stuff, looks like you're got it covered. I believe this is the issue I was having.
