### ISSUE TITLE
bugs report: "strange episode" (Enthusiast version)

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#84]
A whole bunch of weird things happened in succession so I have uploaded a video of the whole thing. A general theme is UI elements not working as expected: not rendering correctly, not responding to clicks. This was true of the desktop timeline, the desktop right-click menu, the desktop file toolbar menu, the VR dashboard menu, VR menu panels. There was also an issue where I became stuck in the floor of the cinema environment and could not see the screen (much) and could not move.
https://youtu.be/3veu-5dAfUU

**Comment by phileday** [comment]
Cheers. I'll try and recreate the issues now.

**Comment by phileday** [comment]
**TimeLine Disappears:**
No Media was selected so the timeline hides. (Noted problem the title of the previously loaded media is still visible. Fix - name of video is now "No Media Loaded!" and the VR playback is mirrored correctly to reprecent this.

**File menu locked:**
Couldn't get it locked but added extra element to unlock it when clicking on other menus.

**Squash menu items**
Mirror and markers have been swapped as the markers is a new feature for Tier 3. This stops them from overlapping.

**Snapshot should be accessible from VR.**
I've added it to the playback menu.

**Mirrormode should be accessible from VR.**
Mirror panel in VR was named Environments. Now changed to Desktop Mirroring.
It is but it is a bit shit at the moment. Needs improvement.

**Switching to Cinema Appears in floor. Resetting and you're still in the floor. Can't change seats either.**
Caused by going to cinema from equirectangualar to Cinema. This has been fixed :)
