### ISSUE TITLE
2.17 bug: 'File>Save Snapshot' doesn't appear to save the snapshot

### ISSUE THREAD

**Issue by NicholasWaterton** [phileday/Festoon#93]
Checking in the file explorer, I'm not able to find the snapshots saved by this feature, as accessed via 'File>Save Snapshot'. However the VR 'save snapshot' button works as expected.

video:
https://www.youtube.com/watch?v=3bpQL8B8lwk&feature=youtu.be

**Comment by phileday** [comment]
I think this is because is takes a little while to save the png and you got to the desktop before it got saved.

What I've done is add a saving pause so you can't use Festoon until it's finished saving and a test to see if there is any file loaded so you can't try and save when there's nothing to save.

Take a look and see if it has helped in the next update :)

**Comment by NicholasWaterton** [comment]
I believe that the image is not saving because I've tried the process shown in the video several times. I'm still not seeing a new image in my desktop folder.

**Comment by phileday** [comment]
This is going to be a different issue then. I've added the pause though which should help. Maybe it's trying to save somewhere else. I'll look at adding the save location to the dialog which might help to pin down the issue.
